macro(detect_os)
  if(EMSCRIPTEN)
    add_compile_definitions(OS_WEB)
    message(STATUS "Building for Web")
  elseif(WIN32)
    add_compile_definitions(OS_WINDOWS)
    add_compile_definitions(WIN32_LEAN_AND_MEAN)
    message(STATUS "Building for Windows")
  elseif(APPLE)
    add_compile_definitions(OS_MACOS)
    enable_language(OBJC)
    enable_language(OBJCXX)
    message(STATUS "Building for MacOS")
  elseif(UNIX AND NOT APPLE)
    add_compile_definitions(INSTRONIMBUS_OS_LINUX)
    message(STATUS "Building for Linux")
  else()
    message(FATAL_ERROR "Unknown / unsupported system!")
  endif()
endmacro()
